apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: test-suhail
  labels:
    app: nginx-test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-test
  type: ClusterIP
